version: '3'

services:
   db:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     command: --default-authentication-plugin=mysql_native_password
     volumes:
       - ./seed:/docker-entrypoint-initdb.d
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
       PMA_HOST: db
       PMA_USER: root
       PMA_PASSWORD: somewordpress
     ports:
       - "82:80"
   wordpress:
     depends_on:
       - db
     image: mattiashem/wp-base:5.3
     ports:
       - "80:8000"
       - "444:8443"
     volumes:
       - ./wp-content:/repo/wp-content
     environment:
       DBHOST: db
       SITENAME: wordpress
       DBPASS: wordpress

