version: '3'

services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: mattiashem/wp-base:latest
     ports:
       - "80:8000"
     restart: always
     volumes:
       - ./:/repo/wp-content
     environment:
       DBHOST: db
       SITENAME: wordpress
       DBPASS: wordpress
       SMTP_HOST: mailgun.com
       SMTP_USER: non@test.com
       SMTP_PASS: password
       SMTP_FROM: non@test.com
   dbseed:
     depends_on:
       - db
     image: mattiashem/dbseed
     volumes:
       - ./seed:/seed
     environment:
       - SQLUSER=wordpress
       - SQLPASS=wordpress
       - SQLDB=wordpress

